---
- name: install opendaylight packages
  yum: name={{ item }} state=present disable_gpg_check=true
  with_items:
    - java-1.7.0-openjdk

#- name: create odl directories
#  file:
#    path: /opt/opendaylight-0.2.2
#    state: "directory"
#    group: root
#    owner: root
#    mode: 0755
   
- name: create odl group
  group: name=odl system=yes state=present

- name: create odl user
  user:
    name: odl
    group: odl
    home: "{{ odl_home }}"
    createhome: "yes"
    system: "yes"
    shell: "/bin/false"

- name: download odl package
  get_url: url={{ odl_pkg_url }} dest=/opt/{{ odl_pkg_name }}

# TODO: unarchive doesn't support strip-component at the moment
# TODO: switch to use untar after support is added.
- name: extract odl package
#  unarchive: src=/opt/{{ odl_pkg_name }} dest={{ odl_home }} group=odl owner=odl mode=0775 copy=no
  command: su -s /bin/sh -c "tar xzf /opt/{{ odl_pkg_name }} -C {{ odl_home }} --strip-components 1 --no-overwrite-dir -k --skip-old-files" odl
  notify:
    - restart odl service

- name: opendaylight systemd file
  template: src=opendaylight.service dest=/usr/lib/systemd/system/opendaylight.service mode=0644

- name: create karaf config
  template:
    src: org.apache.karaf.features.cfg
    dest: "{{ odl_home }}/etc/org.apache.karaf.features.cfg"
    owner: odl
    group: odl
    mode: 0775
  notify:
    - restart odl service

- name: create tomcat config
  template:
    src: tomcat-server.xml
    dest: "{{ odl_home }}/configuration/tomcat-server.xml"
  notify:
    - restart odl service

#- name: restart odl service
#  service: name=opendaylight state=started pattern="opendaylight"
